### ISSUE TITLE
Add more choices for networking

### ISSUE THREAD

**Issue by Arzte** [antonio-malcolm/corgi-scripts#1]
Like connman, and wcid

**Comment by antonio-malcolm** [comment]
It's likely going to be a while before I add support for more interfaces, for command and control of networking. My decision, to use nmcli (NetworkManager), was based largely on four things:

1.) Userbase - I want to cover as many users/use cases as possible, as early on as possible.

2.) Information and Predictability - nmcli provides the most abundant/complete information from the CLI, across the greatest number of networking interfaces and configurations, and how it is displayed/formatted in command responses is unlikely to change anytime soon. To accomplish the former, with tools such as wicd or connman, I'd likely also need to install other CLI tools. For the latter, while I might not need to worry so much about changes to the output and/or format of either connman or wicd-cli, the aforementioned other tools I would need to complete certain bits of data might give cause for greater concern (one of whom even states, outright, "don't rely on the format of our output, for scraping data").

3.) Developer support - NetworkManager is under the Gnome umbrella, and heavily used in production environments. Aside from being entrenched enough for predictable development support, this is also a very good indicator of item 2.

4.) I'm one guy, building and supporting this stuff, and a separate middleware shlib would need to be written to support each option for command and control of the networking, as each not only uses different commands, but also completely different formats for their response data. As such, the flow for obtaining that data, and for parsing that data into the various menus and actions based on it, is _completely_ different, from project to project, which puts a stiff limit on code reusability.

Understand, I'm not at all opposed to supporting other means of controlling and obtaining information about the networking interfaces. In fact, I'd like, _greatly_, for there to be multiple options for support, for _all_ of corgi's features. What's a bit sad, in this case, is that it's one of the few cases for which I have a LOT of options (try managing displays, with any sort of flexibility, outside of XrandR, or SAMBA shares, outside of the core SAMBA project). Unfortunately, time constraints and the need to expand corgi-scripts horizontally (i.e., support a broader range of overall functionality, vs multiple options for a single category of functionality), dictate I stick pretty closely to the four items outlined, above.

**Comment by Arzte** [comment]
Ok
